### ISSUE TITLE
Búsqueda de aplicaciones relacionadas

### ISSUE THREAD

**Issue by Mendez00** [Mendez00/BreathBank#1]
Búsqueda de aplicaciones relacionadas con la que vamos a desarrollar, para hacernos una idea de las diferentes opciones de diseño que tenemos que realizar.
Las 3 aplicaciones seleccionadas son One Deep Breath, Breathe y Exact Breath.
El desarrollo de la elección de estas 3 aplicaciones estará documentado en el fichero "anexos".

**Comment by alvarag** [comment]
Debe documentarse en la memoria (no en anexos), exactamente en la parte de la memoria de "Trabajos Relacionados".
