### ISSUE TITLE
Elección de herramientas

### ISSUE THREAD

**Issue by Mendez00** [Mendez00/BreathBank#2]
A la hora de elegir la herramienta con la que desarrollar el proyecto hay que analizar las funcionalidades de cada una. La característica fundamental es que sea multiplataforma, ya que debemos hacerlos tanto en Android como en IOS.
Tras el estudio, la elección termina siendo Flutter, ya que usa un lenguaje DART, basado en Java, los tutores controlan más esta plataforma, y en relación al diseño los widgets que utiliza sirven tanto para IOS como para Android. 
Otras herramientas como React Native, Xamarin o Ionic también son interesantes, pero no tienen tantos argumentos a favor como FLUTTER.

**Comment by alvarag** [comment]
Recuerda ir documentando todas estas decisiones en la memoria
